{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    (vscode-with-extensions.override {
      vscode = vscodium;
      vscodeExtensions = with vscode-extensions; [
        batisteo.vscode-django
        davidanson.vscode-markdownlint
        docker.docker
        donjayamanne.githistory
        donjayamanne.python-extension-pack
        editorconfig.editorconfig
        github.copilot
        github.copilot-chat
        github.remotehub
        github.vscode-pull-request-github
        golang.go
        hashicorp.terraform
        jnoortheen.nix-ide
        kevinrose.vsc-python-indent
        mads-hartmann.bash-ide-vscode
        mgesbert.python-path
        mhutchie.git-graph
        mkhl.direnv
        ms-azuretools.vscode-containers
        ms-kubernetes-tools.vscode-kubernetes-tools
        ms-python.debugpy
        ms-python.python
        ms-python.vscode-pylance
        ms-python.vscode-python-envs
        ms-toolsai.jupyter
        ms-toolsai.jupyter-keymap
        ms-toolsai.jupyter-renderers
        ms-toolsai.vscode-jupyter-cell-tags
        ms-toolsai.vscode-jupyter-slideshow
        ms-vscode.cmake-tools
        ms-vscode.cpptools
        ms-vscode.cpptools-extension-pack
        ms-vscode.cpptools-themes
        ms-vscode.makefile-tools
        ms-vscode.remote-repositories
        njpwerner.autodocstring
        oderwat.indent-rainbow
        pkief.material-icon-theme
        platformio.platformio-ide
        redhat.ansible
        redhat.vscode-yaml
        rust-lang.rust-analyzer
        tamasfe.even-better-toml
        usernamehw.errorlens
        visualstudioexptteam.intellicode-api-usage-examples
        visualstudioexptteam.vscodeintellicode
        vscodevim.vim
        waderyan.gitblame
        webfreak.debug
        wholroyd.jinja
      ];
    })
  ];
}
