---
name: "test_arm64"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Flake build
      run: |
        cd flakes
        nix build .#nixosConfigurations."nyxpi".config.system.build.toplevel
